package analyzer

import (
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestFieldNamePolicy(t *testing.T) {
	cases := []struct {
		name, source string
		want         int
		fixable      bool
	}{
		{name: "three fields", source: `var _ = struct{A, B, C int}{1, 2, 3}`},
		{name: "four fields", source: `var _ = Quad{1, 2, 3, 4}`, want: 1, fixable: true},
		{name: "anonymous", source: `var _ = struct{A, B, C, D int}{1, 2, 3, 4}`, want: 1, fixable: true},
		{name: "empty", source: `var _ = Quad{}`},
		{name: "keyed", source: `var _ = Quad{D: 4, A: 1}`},
		{name: "map", source: `var _ = map[int]int{1: 2, 3: 4, 5: 6, 7: 8}`},
		{name: "slice", source: `var _ = []int{1, 2, 3, 4}`},
		{name: "array", source: `var _ = [4]int{1, 2, 3, 4}`},
		{name: "named pointer", source: `type Pointer *Quad; var _ = []Pointer{{1, 2, 3, 4}}`, want: 1, fixable: true},
		{name: "pointer", source: `var _ = &Quad{1, 2, 3, 4}`, want: 1, fixable: true},
		{name: "elided type", source: `var _ = []Quad{{1, 2, 3, 4}}`, want: 1, fixable: true},
		{name: "elided pointer", source: `var _ = []*Quad{{1, 2, 3, 4}}`, want: 1, fixable: true},
		{name: "alias", source: `type Alias = Quad; var _ = Alias{1, 2, 3, 4}`, want: 1, fixable: true},
		{name: "pointer alias", source: `type Alias = *Quad; var _ = []Alias{{1, 2, 3, 4}}`, want: 1, fixable: true},
		{
			name:   "generic",
			source: `type Generic[T any] struct{A, B, C, D T}; var _ = Generic[int]{1, 2, 3, 4}`,
			want:   1, fixable: true,
		},
		{
			name:   "type parameter",
			source: `func build[T ~struct{A,B,C,D int}]() T { return T{1,2,3,4} }`,
			want:   1, fixable: true,
		},
		{
			name:    "intersected constraint",
			source:  `type Small struct{A,B,C int}; type Set interface{Small | Quad}; func build[T interface{Set; Quad}]() T { return T{1,2,3,4} }`,
			want:    1,
			fixable: true,
		},
		{
			name:   "union constraint",
			source: `type Other Quad; func build[T Quad | Other]() T { return T{1,2,3,4} }`,
			want:   1, fixable: true,
		},
		{
			name:   "generic slice",
			source: `func build[T ~[]int]() T { return T{1,2,3,4} }`,
		},
		{
			name:   "embedded",
			source: `type Embedded struct{Quad; A, B, C int}; var _ = Embedded{Quad{}, 1, 2, 3}`,
			want:   1, fixable: true,
		},
		{
			name: "blank field", source: `var _ = struct{A, _, C, D int}{1, 2, 3, 4}`, want: 1,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			src := "package fixture\ntype Quad struct{A, B, C, D int}\n" + tc.source
			fset, diagnostics := analyzeSource(t, src)
			if len(diagnostics) != tc.want {
				t.Fatalf("diagnostics = %v, want %d", diagnostics, tc.want)
			}
			if tc.fixable {
				fixed := applyFixes(t, src, fset, diagnostics)
				_, remaining := analyzeSource(t, fixed)
				if len(remaining) != 0 {
					t.Fatalf("fixed source still has diagnostics: %v", remaining)
				}
			}
			for _, diagnostic := range diagnostics {
				if got := len(diagnostic.SuggestedFixes) > 0; got != tc.fixable {
					t.Errorf("fixable = %v, want %v", got, tc.fixable)
				}
			}
		})
	}
}

func TestGeneratedFilesAreSkipped(t *testing.T) {
	src := "// Code generated by fixture. DO NOT EDIT.\npackage fixture\nvar _ = struct{A,B,C,D int}{1,2,3,4}"
	_, diagnostics := analyzeSource(t, src)
	if len(diagnostics) != 0 {
		t.Fatalf("generated source produced diagnostics: %v", diagnostics)
	}
}

func analyzeSource(t *testing.T, source string) (*token.FileSet, []analysis.Diagnostic) {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "fixture.go", source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	info := &types.Info{Types: make(map[ast.Expr]types.TypeAndValue)}
	cfg := types.Config{Importer: importer.Default()}
	pkg, err := cfg.Check("fixture", fset, []*ast.File{file}, info)
	if err != nil {
		t.Fatal(err)
	}
	var diagnostics []analysis.Diagnostic
	pass := &analysis.Pass{
		Fset: fset, Files: []*ast.File{file}, TypesInfo: info, Pkg: pkg,
		Report: func(diagnostic analysis.Diagnostic) { diagnostics = append(diagnostics, diagnostic) },
	}
	if _, err := Analyzer.Run(pass); err != nil {
		t.Fatal(err)
	}
	return fset, diagnostics
}
